//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AltinnDesktopTool.View {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AltinnDesktopTool.View.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobilnummer / Epost / Organisasjonsnummer:.
        /// </summary>
        public static string ContactInformationSearchLabel {
            get {
                return ResourceManager.GetString("ContactInformationSearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopier til tekstformat.
        /// </summary>
        public static string CopyPlainTextTooltip {
            get {
                return ResourceManager.GetString("CopyPlainTextTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopier til excelformat.
        /// </summary>
        public static string CopyToExcelTooltip {
            get {
                return ResourceManager.GetString("CopyToExcelTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-post.
        /// </summary>
        public static string EMail {
            get {
                return ResourceManager.GetString("EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applikasjon for oppslag i kontaktinformasjon for virksomheter.
        /// </summary>
        public static string HeaderText {
            get {
                return ResourceManager.GetString("HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ved å fylle inn e-post/organisasjonsnummer/telefonnummer har man mulighet til å gjøre oppslag i Altinns kontaktinformasjon for virksomheter. Målet er å hjelpe kunder med å finne ut hvorfor de får varslinger fra Altinns miljøer.
        ///
        ///Hvis du har spørsmål / bugs, gå til https://github.com/Altinn/altinn-desktop-tool.
        /// </summary>
        public static string InfoText {
            get {
                return ResourceManager.GetString("InfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingen data funnet.
        /// </summary>
        public static string NoDataText {
            get {
                return ResourceManager.GetString("NoDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-post.
        /// </summary>
        public static string OfficialContactsGridColumnEmail {
            get {
                return ResourceManager.GetString("OfficialContactsGridColumnEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobilnummer.
        /// </summary>
        public static string OfficialContactsGridColumnMobile {
            get {
                return ResourceManager.GetString("OfficialContactsGridColumnMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felles kontaktinformasjon.
        /// </summary>
        public static string OfficialContactsTitle {
            get {
                return ResourceManager.GetString("OfficialContactsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navn.
        /// </summary>
        public static string OrganizationGridColumnName {
            get {
                return ResourceManager.GetString("OrganizationGridColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisasjonsnummer.
        /// </summary>
        public static string OrganizationGridColumnOrganizationNumber {
            get {
                return ResourceManager.GetString("OrganizationGridColumnOrganizationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string OrganizationGridColumnType {
            get {
                return ResourceManager.GetString("OrganizationGridColumnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to organisasjonsnummer.
        /// </summary>
        public static string OrganizationNumber {
            get {
                return ResourceManager.GetString("OrganizationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-post.
        /// </summary>
        public static string PersonalContactsGridColumnEmail {
            get {
                return ResourceManager.GetString("PersonalContactsGridColumnEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobilnummer.
        /// </summary>
        public static string PersonalContactsGridColumnMobile {
            get {
                return ResourceManager.GetString("PersonalContactsGridColumnMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navn.
        /// </summary>
        public static string PersonalContactsGridColumnName {
            get {
                return ResourceManager.GetString("PersonalContactsGridColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fødselsnummer.
        /// </summary>
        public static string PersonalContactsGridColumnSsn {
            get {
                return ResourceManager.GetString("PersonalContactsGridColumnSsn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Din kontaktinformasjon.
        /// </summary>
        public static string PersonalContactsTitle {
            get {
                return ResourceManager.GetString("PersonalContactsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mobilnummer.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollegiver (SSN/Organisasjonsnummer):.
        /// </summary>
        public static string Reportee {
            get {
                return ResourceManager.GetString("Reportee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string RoleGridColumnRoleDefinitionId {
            get {
                return ResourceManager.GetString("RoleGridColumnRoleDefinitionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beskrivelse.
        /// </summary>
        public static string RoleGridColumnRoleDescription {
            get {
                return ResourceManager.GetString("RoleGridColumnRoleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolle.
        /// </summary>
        public static string RoleGridColumnRoleName {
            get {
                return ResourceManager.GetString("RoleGridColumnRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string RoleGridColumnRoleType {
            get {
                return ResourceManager.GetString("RoleGridColumnRoleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Søk.
        /// </summary>
        public static string SearchButtonText {
            get {
                return ResourceManager.GetString("SearchButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det blir ikke utført noe søk når søketeksten er tom..
        /// </summary>
        public static string SearchLabelEmptySearch {
            get {
                return ResourceManager.GetString("SearchLabelEmptySearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API nøkkelen som benyttes har ikke rettigheter til å utføre søk..
        /// </summary>
        public static string SearchLabelErrorForbidden {
            get {
                return ResourceManager.GetString("SearchLabelErrorForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det oppstod en ukjent feil under søket. .
        /// </summary>
        public static string SearchLabelErrorGeneralError {
            get {
                return ResourceManager.GetString("SearchLabelErrorGeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Søket inneholder ugyldig input.
        /// </summary>
        public static string SearchLabelErrorInvalidInput {
            get {
                return ResourceManager.GetString("SearchLabelErrorInvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Søket ga en feilmelding som indikerer at organisasjonen ikke finnes..
        /// </summary>
        public static string SearchLabelErrorOrganizationNotFound {
            get {
                return ResourceManager.GetString("SearchLabelErrorOrganizationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det oppstod en feil ved søk. Vennligst forsøk igjen..
        /// </summary>
        public static string SearchLabelErrorSearch {
            get {
                return ResourceManager.GetString("SearchLabelErrorSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det oppstod en feil relatert til autorisasjon. Forsøk igjen..
        /// </summary>
        public static string SearchLabelErrorUnauthorized {
            get {
                return ResourceManager.GetString("SearchLabelErrorUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Søker etter {0}.
        /// </summary>
        public static string SearchLabelResultat {
            get {
                return ResourceManager.GetString("SearchLabelResultat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velg alle.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollehaver (SSN/Organisasjonsnummer):.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktinformasjon.
        /// </summary>
        public static string TabKontaktinformasjon {
            get {
                return ResourceManager.GetString("TabKontaktinformasjon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roller.
        /// </summary>
        public static string TabRoller {
            get {
                return ResourceManager.GetString("TabRoller", resourceCulture);
            }
        }
    }
}
