//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AltinnDesktopTool.View ***REMOVED***
    using System;
    
    
***REMOVED***
    ///   A strongly-typed resource class, for looking up localized strings, etc.
***REMOVED***
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources ***REMOVED***
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() ***REMOVED***
***REMOVED***
        
    ***REMOVED***
        ///   Returns the cached ResourceManager instance used by this class.
    ***REMOVED***
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager ***REMOVED***
            get ***REMOVED***
                if (object.ReferenceEquals(resourceMan, null)) ***REMOVED***
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AltinnDesktopTool.View.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
        ***REMOVED***
                return resourceMan;
    ***REMOVED***
***REMOVED***
        
    ***REMOVED***
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
    ***REMOVED***
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture ***REMOVED***
            get ***REMOVED***
                return resourceCulture;
    ***REMOVED***
            set ***REMOVED***
                resourceCulture = value;
    ***REMOVED***
***REMOVED***
        
    ***REMOVED***
        ///   Looks up a localized string similar to .
    ***REMOVED***
        public static string ApplicationName ***REMOVED***
            get ***REMOVED***
                return ResourceManager.GetString("ApplicationName", resourceCulture);
    ***REMOVED***
***REMOVED***
        
    ***REMOVED***
        ///   Looks up a localized string similar to Kopier til tekstformat.
    ***REMOVED***
        public static string CopyPlainTextTooltip ***REMOVED***
            get ***REMOVED***
                return ResourceManager.GetString("CopyPlainTextTooltip", resourceCulture);
    ***REMOVED***
***REMOVED***
        
    ***REMOVED***
        ///   Looks up a localized string similar to Kopier til excelformat.
    ***REMOVED***
        public static string CopyToExcelTooltip ***REMOVED***
            get ***REMOVED***
                return ResourceManager.GetString("CopyToExcelTooltip", resourceCulture);
    ***REMOVED***
***REMOVED***
        
    ***REMOVED***
        ///   Looks up a localized string similar to e-post.
    ***REMOVED***
        public static string EMail ***REMOVED***
            get ***REMOVED***
                return ResourceManager.GetString("EMail", resourceCulture);
    ***REMOVED***
***REMOVED***
        
    ***REMOVED***
        ///   Looks up a localized string similar to Applikasjon for oppslag i kontaktinformasjon for virksomheter.
    ***REMOVED***
        public static string HeaderText ***REMOVED***
            get ***REMOVED***
                return ResourceManager.GetString("HeaderText", resourceCulture);
    ***REMOVED***
***REMOVED***
        
    ***REMOVED***
        ///   Looks up a localized string similar to Ved å fylle inn e-post/organisasjonsnummer/telefonnummer har man mulighet til å gjøre oppslag i Altinns kontaktinformasjon for virksomheter. Målet er å hjelpe kunder med å finne ut hvorfor de får varslinger fra Altinns miljøer.
        ///
        ///Kontakt Erlend Oksvoll (eok@brreg.no) ved spørsmål!.
    ***REMOVED***
        public static string InfoText ***REMOVED***
            get ***REMOVED***
                return ResourceManager.GetString("InfoText", resourceCulture);
    ***REMOVED***
***REMOVED***
        
    ***REMOVED***
        ///   Looks up a localized string similar to Ingen data funnet.
    ***REMOVED***
        public static string NoDataText ***REMOVED***
            get ***REMOVED***
                return ResourceManager.GetString("NoDataText", resourceCulture);
    ***REMOVED***
***REMOVED***
        
    ***REMOVED***
        ///   Looks up a localized string similar to E-post.
    ***REMOVED***
        public static string OfficialContactsGridColumnEmail ***REMOVED***
            get ***REMOVED***
                return ResourceManager.GetString("OfficialContactsGridColumnEmail", resourceCulture);
    ***REMOVED***
***REMOVED***
        
    ***REMOVED***
        ///   Looks up a localized string similar to Mobilnummer.
    ***REMOVED***
        public static string OfficialContactsGridColumnMobile ***REMOVED***
            get ***REMOVED***
                return ResourceManager.GetString("OfficialContactsGridColumnMobile", resourceCulture);
    ***REMOVED***
***REMOVED***
        
    ***REMOVED***
        ///   Looks up a localized string similar to Felles kontaktinformasjon.
    ***REMOVED***
        public static string OfficialContactsTitle ***REMOVED***
            get ***REMOVED***
                return ResourceManager.GetString("OfficialContactsTitle", resourceCulture);
    ***REMOVED***
***REMOVED***
        
    ***REMOVED***
        ///   Looks up a localized string similar to Navn.
    ***REMOVED***
        public static string OrganizationGridColumnName ***REMOVED***
            get ***REMOVED***
                return ResourceManager.GetString("OrganizationGridColumnName", resourceCulture);
    ***REMOVED***
***REMOVED***
        
    ***REMOVED***
        ///   Looks up a localized string similar to Organisasjonsnummer.
    ***REMOVED***
        public static string OrganizationGridColumnOrganizationNumber ***REMOVED***
            get ***REMOVED***
                return ResourceManager.GetString("OrganizationGridColumnOrganizationNumber", resourceCulture);
    ***REMOVED***
***REMOVED***
        
    ***REMOVED***
        ///   Looks up a localized string similar to Type.
    ***REMOVED***
        public static string OrganizationGridColumnType ***REMOVED***
            get ***REMOVED***
                return ResourceManager.GetString("OrganizationGridColumnType", resourceCulture);
    ***REMOVED***
***REMOVED***
        
    ***REMOVED***
        ///   Looks up a localized string similar to organisasjonsnummer.
    ***REMOVED***
        public static string OrganizationNumber ***REMOVED***
            get ***REMOVED***
                return ResourceManager.GetString("OrganizationNumber", resourceCulture);
    ***REMOVED***
***REMOVED***
        
    ***REMOVED***
        ///   Looks up a localized string similar to E-post.
    ***REMOVED***
        public static string PersonalContactsGridColumnEmail ***REMOVED***
            get ***REMOVED***
                return ResourceManager.GetString("PersonalContactsGridColumnEmail", resourceCulture);
    ***REMOVED***
***REMOVED***
        
    ***REMOVED***
        ///   Looks up a localized string similar to Mobilnummer.
    ***REMOVED***
        public static string PersonalContactsGridColumnMobile ***REMOVED***
            get ***REMOVED***
                return ResourceManager.GetString("PersonalContactsGridColumnMobile", resourceCulture);
    ***REMOVED***
***REMOVED***
        
    ***REMOVED***
        ///   Looks up a localized string similar to Navn.
    ***REMOVED***
        public static string PersonalContactsGridColumnName ***REMOVED***
            get ***REMOVED***
                return ResourceManager.GetString("PersonalContactsGridColumnName", resourceCulture);
    ***REMOVED***
***REMOVED***
        
    ***REMOVED***
        ///   Looks up a localized string similar to Fødselsnummer.
    ***REMOVED***
        public static string PersonalContactsGridColumnSsn ***REMOVED***
            get ***REMOVED***
                return ResourceManager.GetString("PersonalContactsGridColumnSsn", resourceCulture);
    ***REMOVED***
***REMOVED***
        
    ***REMOVED***
        ///   Looks up a localized string similar to Din kontaktinformasjon.
    ***REMOVED***
        public static string PersonalContactsTitle ***REMOVED***
            get ***REMOVED***
                return ResourceManager.GetString("PersonalContactsTitle", resourceCulture);
    ***REMOVED***
***REMOVED***
        
    ***REMOVED***
        ///   Looks up a localized string similar to mobilnummer.
    ***REMOVED***
        public static string PhoneNumber ***REMOVED***
            get ***REMOVED***
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
    ***REMOVED***
***REMOVED***
        
    ***REMOVED***
        ///   Looks up a localized string similar to Søk.
    ***REMOVED***
        public static string SearchButtonText ***REMOVED***
            get ***REMOVED***
                return ResourceManager.GetString("SearchButtonText", resourceCulture);
    ***REMOVED***
***REMOVED***
        
    ***REMOVED***
        ///   Looks up a localized string similar to Det blir ikke utført noe søk når søketeksten er tom..
    ***REMOVED***
        public static string SearchLabelEmptySearch ***REMOVED***
            get ***REMOVED***
                return ResourceManager.GetString("SearchLabelEmptySearch", resourceCulture);
    ***REMOVED***
***REMOVED***
        
    ***REMOVED***
        ///   Looks up a localized string similar to API nøkkelen som benyttes har ikke rettigheter til å utføre søk..
    ***REMOVED***
        public static string SearchLabelErrorForbidden ***REMOVED***
            get ***REMOVED***
                return ResourceManager.GetString("SearchLabelErrorForbidden", resourceCulture);
    ***REMOVED***
***REMOVED***
        
    ***REMOVED***
        ///   Looks up a localized string similar to Det oppstod en ukjent feil under søket. .
    ***REMOVED***
        public static string SearchLabelErrorGeneralError ***REMOVED***
            get ***REMOVED***
                return ResourceManager.GetString("SearchLabelErrorGeneralError", resourceCulture);
    ***REMOVED***
***REMOVED***
        
    ***REMOVED***
        ///   Looks up a localized string similar to Søket ga en feilmelding som indikerer at organisasjonen ikke finnes..
    ***REMOVED***
        public static string SearchLabelErrorOrganizationNotFound ***REMOVED***
            get ***REMOVED***
                return ResourceManager.GetString("SearchLabelErrorOrganizationNotFound", resourceCulture);
    ***REMOVED***
***REMOVED***
        
    ***REMOVED***
        ///   Looks up a localized string similar to Det oppstod en feil ved søk. Vennligst forsøk igjen..
    ***REMOVED***
        public static string SearchLabelErrorSearch ***REMOVED***
            get ***REMOVED***
                return ResourceManager.GetString("SearchLabelErrorSearch", resourceCulture);
    ***REMOVED***
***REMOVED***
        
    ***REMOVED***
        ///   Looks up a localized string similar to Det oppstod en feil relatert til autorisasjon. Forsøk igjen..
    ***REMOVED***
        public static string SearchLabelErrorUnauthorized ***REMOVED***
            get ***REMOVED***
                return ResourceManager.GetString("SearchLabelErrorUnauthorized", resourceCulture);
    ***REMOVED***
***REMOVED***
        
    ***REMOVED***
        ///   Looks up a localized string similar to Søker etter ***REMOVED***0***REMOVED***.
    ***REMOVED***
        public static string SearchLabelResultat ***REMOVED***
            get ***REMOVED***
                return ResourceManager.GetString("SearchLabelResultat", resourceCulture);
    ***REMOVED***
***REMOVED***
        
    ***REMOVED***
        ///   Looks up a localized string similar to Velg alle.
    ***REMOVED***
        public static string SelectAll ***REMOVED***
            get ***REMOVED***
                return ResourceManager.GetString("SelectAll", resourceCulture);
    ***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
